/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.component_two;

public class Thing {
    public void doIt() {
        System.out.println("component_two: " + Thing.class.toString() + 
            " loaded by " + Thing.class.getClassLoader() + 
            " running on thread " + Thread.currentThread().getName() + 
            " Thing did it!");
    }
}
